version: '3.4'

services:
  sdev220:
    image: sdev220
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 M05\CS_Containers_CICD\helloworld.py "]
    ports:
      - 5678:5678
